steps:
- name: "gcr.io/cloud-builders/docker"
  args: ["build","-f","Dockerfile.enricher","-t","gcr.io/${_PROJECT_ID}/paranoid-enricher:${_TAG}","."]
images:
- "gcr.io/${_PROJECT_ID}/paranoid-enricher:${_TAG}"
