routing:
  force_gpt5_languages: ["fi"]
  critical_topics:
    - federal reserve
    - ecb
    - suomen pankki
    - keskuspankki
    - interest rate
    - korko
  complexity_threshold: 0.50
  risk_threshold: 0.40
  min_source_trust_for_llm: 0.20

budget:
  currency: EUR
  deepseek_monthly: 20
  gpt5_monthly: 10

quality:
  min_cards_with_why_it_matters: 0.80
  require_sources_min: 2
  max_cards_per_batch: 100

cache:
  dir: ".cache/hybrid"
  ttl_hours: 72
  prompt_version: "v1"

output:
  newswire: "artifacts/report.enriched.json"

# Provider configurations
providers:
  deepseek:
    type: deepseek
    model: deepseek-r1
    max_output_tokens: 850

  gpt5_cursor:
    type: cursor
    base_url: ${CURSOR_BASE_URL}
    api_key_env: CURSOR_API_KEY
    model: ${CURSOR_GPT5_MODEL}
    max_output_tokens: ${CURSOR_MAX_TOKENS}
    timeout_s: ${CURSOR_TIMEOUT_S}

# Updated routing with force_gpt5_languages
routing:
  force_gpt5_languages: ["fi"]     # kaikki suomenkielinen → GPT-5 (Cursor)
  critical_topics:
    - fed
    - ecb
    - "suomen pankki"
    - korko
    - "central banking"
  risk_threshold: 0.40
  complexity_threshold: 0.50

# Quality validation using Cursor GPT-5
quality:
  validator: gpt5_cursor            # käytä Cursor GPT-5 tarkistukseen
  fallback_on_fail: true
  cache_ttl_hours: 72
