model:
  name: "paranoid_v5"
  targets:
    - name: "sensitive_class"
      type: "binary"
      algorithm: "logistic"
      threshold: 0.5
    - name: "suppression_event_6w" 
      type: "binary"
      algorithm: "logistic"
      threshold: 0.5
    - name: "narrative_shift_4w"
      type: "binary"
      algorithm: "logistic"
      threshold: 0.5
    - name: "conflict_intensity"
      type: "continuous"
      algorithm: "ridge"

features:
  numerical:
    - propaganda_index
    - framing_intensity
    - coordination_index
    - suppression_pressure_index
    - secret_history_index
    - finance_pressure_index
    - network_density
    - geospatial_risk
    - precursor_score
    - external_sanction_index
    - media_censorship_score
  
  categorical:
    - region
    - actor_group
  
  engineered:
    enable: true
    interactions: true
    temporal: true

quality_gates:
  auc_minimum: 0.86
  pr_auc_minimum: 0.80
  brier_maximum: 0.20
  ece_maximum: 0.05
  delta_auc_maximum: 0.10

validation:
  method: "temporal_cv"
  n_splits: 5
  test_size: 0.2

output:
  save_plots: true
  save_feature_importance: true
  save_calibration: true