model:
  name: "paranoid_v5"

targets:
  - "sensitive_class"
  - "suppression_event_6w"
  - "narrative_shift_4w"
  - "conflict_intensity"

features:
  numerical:
    - propaganda_index
    - framing_intensity
    - coordination_index
    - suppression_pressure_index
    - secret_history_index
    - finance_pressure_index
    - network_density
    - geospatial_risk
    - precursor_score
    - external_sanction_index
    - media_censorship_score
  
  categorical:
    - region
    - actor_group
  
  interactions:
    - ["propaganda_index", "framing_intensity"]
    - ["coordination_index", "suppression_pressure_index"]

quality_gates:
  auc_min: 0.86
  pr_auc_min: 0.80
  brier_max: 0.20
  ece_max: 0.05
  delta_auc_max: 0.10

validation:
  method: "temporal_cv"
  n_splits: 5
  test_size: 0.2

cv_folds: 5
seed: 42
calibration: "platt"

output:
  save_plots: true
  save_feature_importance: true
  save_calibration: true