name: ci

on:
  push:
    branches: [ main, master ]
  pull_request:

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install deps
        run: |
          python -m venv .venv
          . .venv/bin/activate
          pip install -U pip
          pip install -r requirements.txt
          pip install -r requirements-dev.txt
      - name: Lint
        run: |
          . .venv/bin/activate
          ruff check .
      - name: Tests
        run: |
          . .venv/bin/activate
          pytest -q
      - name: Enrich report (optional)
        if: ${{ vars.USE_GPT5 == 'true' && hashFiles('artifacts/signal.raw.json') != '' && hashFiles('artifacts/feed_item_schema.json') != '' }}
        env:
          CURSOR_API_KEY: ${{ secrets.CURSOR_API_KEY }}
          CURSOR_API_BASE: ${{ vars.CURSOR_API_BASE }}
          CURSOR_MODEL: ${{ vars.CURSOR_MODEL }}
        run: |
          . .venv/bin/activate
          make enrich || (echo "enrich failed" && exit 1)
      - name: Upload enriched artifact (if present)
        if: ${{ hashFiles('artifacts/report.enriched.json') != '' }}
        uses: actions/upload-artifact@v4
        with:
          name: report.enriched.json
          path: artifacts/report.enriched.json
      - name: Train (linear cv=4)
        run: |
          . .venv/bin/activate
          python -m src.cli train --csv ./data/data.csv --model linear --cv 4
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: model-artifacts
          path: artifacts/*
