name: Validate News
on: [push, pull_request]
jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Install deps
        run: |
          npm ci || npm i
      - name: Validate content (Hersh + Dark tolerance)
        run: |
          make style-check || true
          make feeds || true
          make validate-news || true
        if: github.event_name == 'pull_request'
